alias ll='ls -la'
alias pp='cat /sys/class/drm/card0/device/power_profile'
alias pacaur='pacaur --noedit'
alias repo='$HOME/bin/repo'
alias gt='gnome-terminal'
alias flux='xflux -l 47.4719 -g 19.0503'
alias clean_pac='sudo pacman -Rsn $(pacman -Qdtq)'
